version: '3.8'

services:
  dashboard:
    build: .
    ports:
      - "8010:8010"
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    command: uvicorn main:app --host 0.0.0.0 --port 8010
    restart: unless-stopped

  webhook:
    build: .
    ports:
      - "8011:8011"
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    command: uvicorn webhook_server:app --host 0.0.0.0 --port 8011
    restart: unless-stopped 